---
draft: true
title: "Study about de/retransition"
description: |
  A qualitative study of the experiences and needs of people who have experienced detransition in some form
---

<span class="status-badge">Ongoing</span> <span class="listing-tags">Qualitative studies</span>

## In brief

Detransition and retransition are terms used in different ways. They may refer to the discontinuation of medical gender-affirming treatment to transition from one gender to another. Detransition and retransition may also mean that someone goes back to identifying with the sex they were assigned with at birth, that the gender identity has become less important to them, or that the person has started to identify in a different way.

Some also distinguish between medical detransition, which refers to the discontinuation of medical gender-confirming treatments, and social detransition, which refers to a process of changing social aspects of a previous social transition. In some cases the concept of retransition is also used, which means making a transition after having previously made one or more transitions, but not necessarily back to the gender assigned at birth.

Within the above groups there may also be individuals who regret previously completed treatments or other steps they have taken during their process. These concepts have been used in different ways in the literature, which has led to some confusion around their meaning.

## Why it matters

In Sweden, the debate about gender-affirming care, especially for young people, has intensified in recent years. In February 2022 the National Board of Health and Welfare issued new recommendations for hormonal treatment for young people, which are considerably stricter than before. It is now recommended that hormonal treatment be offered to minors only in exceptional cases, and otherwise only in the context of a research project.

The changed recommendations are based, among other things, on SBU's compilation of evidence for the state of gender-affirming care for young people. It is stated there that it is not possible to determine how common it is for people to change their gender identity, stop treatment, or in some aspect regret it. Concern is also expressed about a large number of detransitioned people whose experiences and needs are not documented.

## What we do

The aim of the study is to explore the experiences and needs of people who have experienced de/retransition in some form. We see a great need to conduct this qualitative study first, in order to be able to measure the prevalence of detransitioned people quantitatively and systematically in the long term.

Increased knowledge in this area is also important in order to further develop gender-affirming healthcare, both during the assessment period and after receiving a diagnosis and gender-affirming treatment.

## Taking part

## What we have found

## For researchers

| | |
| --- | --- |
| Design | Qualitative multicentre study |
| Presented | Karinsdotter A, Indremo M, Pagoni K, Öster C, Papadopoulos FC. Studie om de/re/omtransition: en multicenter kvalitativ studie i Sverige. 15th SFTH conference, Gothenburg, 9–11 November 2022 |
| Status | |

## Team and funding

## Contact

[fotis.papadopoulos@uu.se](mailto:fotis.papadopoulos@uu.se)

## På svenska

### Kort om studien

Detransition och retransition är begrepp som används på olika sätt. Det kan innebära att avbryta medicinsk könsbekräftande behandling för att transitionera från ett kön till ett annat. Detransition och retransition kan också innebära att man återgår till att identifiera sig med det kön man tilldelades vid födseln, att könsidentiteten har fått mindre betydelse eller att man börjat identifiera sig på ett annat sätt.

Vissa skiljer också mellan medicinsk detransition, som avser att avbryta just medicinska könsbekräftande behandlingar, och social detransition, som avser en process att förändra sociala aspekter i en tidigare social transition. I vissa fall används också begreppet omtransition, vilket innebär att göra en transition efter att tidigare ha gjort en eller flera transitioner, men inte nödvändigtvis tillbaka till det vid födseln tilldelade könet.

Inom ovanstående grupper kan det också finnas individer som ångrar tidigare genomförda behandlingar eller andra steg de tagit under sin process. Dessa begrepp har dock använts på olika sätt i litteraturen, vilket lett till viss förvirring kring begreppens innebörd.

### Varför studien behövs

I Sverige har debatten om den könsbekräftande vården, framför allt för unga, varit intensiv de senaste åren. I februari 2022 kom också Socialstyrelsen med nya rekommendationer för hormonell behandling för unga, som är betydligt striktare än tidigare. Man rekommenderar nu att hormonell behandling endast i undantagsfall ska kunna erbjudas minderåriga personer och då enbart inom ramen för forskning.

De förändrade rekommendationerna grundar sig bland annat i SBU:s sammanställning av evidensläget för könsbekräftande vård för unga. Man konstaterar där att det bland annat inte går att avgöra hur vanligt det är att personer ändrar sin könsidentitet, avbryter behandlingar eller i någon aspekt ångrar den. Man uttrycker vidare oro för ett stort mörkertal av detransitionerade vars upplevelser och behov inte är kartlagda.

### Så går det till

Syftet med studien är att kartlägga erfarenheter och behov hos personer som har erfarenhet av detransition i någon form. Vi ser ett stort behov av att initialt genomföra denna kvalitativa studie för att på sikt kunna mäta förekomst av detransitionerade på ett systematiskt sätt. Ökad kunskap kring området är också viktigt för att kunna utveckla den könsbekräftande vården både under utredning och efter eventuell diagnos och könsbekräftande behandling.
