

name: Dissemination Post
description: Submit a new dissemination blog post for the website
title: "[Dissemination] "
labels:
  - dissemination
  - blog
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Write the title of your post
      placeholder: "Enter the post title"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief summary of the post shown on the blog summary page
      placeholder: "Enter a short summary"
    validations:
      required: true
  - type: textarea
    id: main-content
    attributes:
      label: Main Content
      description: Write your post content here. This will be the main text of your blog post.
      placeholder: "Enter the main content of your post"
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      description: Your name, shown as the author of the post
      placeholder: "Enter your name"
    validations:
      required: true
